export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as NewEventScreen } from './NewEventScreen'
export { default as DashboardScreen } from './DashboardScreen'
//export { default as InfoEventsScreen } from './InfoEventScreen'
